// packages/components-test-vue/src-vue/material/Tooltip.vue
<script setup lang="ts">
import {
  TooltipProvider,
  TooltipRoot,
  TooltipTrigger,
  TooltipContent,
} from "radix-vue";

import { cn } from "../lib/utils";

interface Props {
  class?: string;
  sideOffset?: number;
}

const props = withDefaults(defineProps<Props>(), {
  class: undefined,
  sideOffset: 4,
});
</script>

<template>
  <TooltipProvider>
    <TooltipRoot>
      <slot name="trigger">
        <TooltipTrigger />
      </slot>
      <TooltipContent
        :side-offset="props.sideOffset"
        :class="
          cn(
            'bg-primary text-primary-foreground animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 z-50 overflow-hidden rounded-[4px] px-3 py-1.5 text-xs shadow-[0_2px_4px_rgba(0,0,0,0.1)]',
            props.class
          )
        "
      >
        <slot />
      </TooltipContent>
    </TooltipRoot>
  </TooltipProvider>
</template>

// packages/components-test/src/material/tooltip.tsx
import * as React from "react";
import * as TooltipPrimitive from "@radix-ui/react-tooltip";

import { cn } from "../lib/utils";

const TooltipProvider = TooltipPrimitive.Provider;

const Tooltip = TooltipPrimitive.Root;

const TooltipTrigger = TooltipPrimitive.Trigger;

/**
 * Material Design Tooltip Content
 * - Small rounded corners (4px)
 * - Subtle shadow
 * - 200ms fade animation
 */
const TooltipContent = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <TooltipPrimitive.Content
    ref={ref}
    sideOffset={sideOffset}
    className={cn(
      "bg-primary text-primary-foreground animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 z-50 overflow-hidden rounded-[4px] px-3 py-1.5 text-xs shadow-[0_2px_4px_rgba(0,0,0,0.1)]",
      className
    )}
    {...props}
  />
));
TooltipContent.displayName = TooltipPrimitive.Content.displayName;

export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider };
